### ISSUE TITLE
目前已知OICQ問題

### ISSUE THREAD

**Issue by Zokhoi** [Zokhoi/LilyWhiteBot#1]
From WhitePhosphorus in Wikipedia-zh community chat
目前使用的 qq 部分是 oicq，已知问题包括

bug:
- [x] qq 语音发不出

enhancement: 
- [x] qq 回复仍然显示成@

wont fix:
- qq 文件收不到
- qq 发送文件给 discord/tg 只能收到链接

等

**Comment by Joch2520** [comment]
語音現在能發，但是使用silk格式
可能需要使用[wx-voice](https://github.com/Ang-YC/wx-voice)解碼

**Comment by Joch2520** [comment]
qq 文件收不到 是OICQ未支援群文件發送功能
![image](https://user-images.githubusercontent.com/20432565/110940354-bcfa5e80-8371-11eb-8d49-70b2632af824.png)
參考此處 [90.如何发送多媒体内容(CQ码)](https://github.com/takayama-lily/oicq/wiki/90.%E5%A6%82%E4%BD%95%E5%8F%91%E9%80%81%E5%A4%9A%E5%AA%92%E4%BD%93%E5%86%85%E5%AE%B9(CQ%E7%A0%81))

**Comment by Joch2520** [comment]
![image](https://user-images.githubusercontent.com/20432565/111081536-c4bb2e00-853e-11eb-804f-de94a5d2e0ea.png)
![image](https://user-images.githubusercontent.com/20432565/111081483-81f95600-853e-11eb-93af-7772ddbd1aa5.png)

直接i++跳過CQ:reply後面的一個消息段似乎不行。
需要再做調查。

**Comment by Joch2520** [comment]
目前會檢查消息回覆後一消息段是否at，是則直接跳過。

**Comment by Zokhoi** [comment]
![image](https://user-images.githubusercontent.com/20432565/192105951-cb5b5861-18e0-4bff-a1af-a8901ea0540f.png)
qq發送文件可能檔案大小極大，因此只提供鏈接，不考慮使用雲端存儲伺服器如圖床等。
