### ISSUE TITLE
ReferenceError: qqConfig is not defined

### ISSUE THREAD

**Issue by Bengcord** [Zokhoi/LilyWhiteBot#2]
![](https://cdn.jsdelivr.net/gh/Bengcord/ouwtown@main/Image/20210805204634.png)
我的Config：
![](https://cdn.jsdelivr.net/gh/Bengcord/ouwtown@main/Image/20210805204721.png)
均已正常填写，但无法启动

**Comment by Zokhoi** [comment]
本程序默認使用 cqsocketapi 與酷q配套運行，要使用 OICQ 需要刪除 config 下 apiRoot 至 port 部份
