### ISSUE TITLE
关于uguu图床的api更改

### ISSUE THREAD

**Issue by SirnoChan** [Zokhoi/LilyWhiteBot#6]
uguu图床软件的使用方式经过几年的变化，已与之前大相径庭，按照目前示例配置文件里的说明是无法使用uguu的。可参考[我之前提的pr](https://github.com/infnan/LilyWhiteBot/pull/32)以及uguu的仓库。本人码力有限，只能借其他人的力了。

**Comment by Zokhoi** [comment]
已更新
